Repository a-romantic-cat/Back-end, pull requests merged in 2024-01, with the labels that each got.

#3 Ci/1
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/conf.d/client_max_body_size.conf
  .platform/nginix.conf
  Procfile
Labels: :sparkles:feat, :construction_worker: ci

#11 ✨Swagger 세팅
  build.gradle
  src/main/java/aromanticcat/umcproject/config/SwaggerConfig.java
Labels: :sparkles:feat

#13 ✨ entity 생성
  src/main/java/aromanticcat/umcproject/UmcProjectApplication.java
  src/main/java/aromanticcat/umcproject/entity/BaseEntity.java
  src/main/java/aromanticcat/umcproject/entity/Friend.java
  src/main/java/aromanticcat/umcproject/entity/ItemBox.java
  src/main/java/aromanticcat/umcproject/entity/Member.java
  src/main/java/aromanticcat/umcproject/entity/MemberMission.java
  src/main/java/aromanticcat/umcproject/entity/Mission.java
  src/main/java/aromanticcat/umcproject/entity/NangmanLetter.java
  src/main/java/aromanticcat/umcproject/entity/NangmanReply.java
  src/main/java/aromanticcat/umcproject/entity/Reward.java
  src/main/resources/application.yml
Labels: :sparkles:feat

#20 ✨ 낭만 우편함 편지 등록 API 구현
  src/main/java/aromanticcat/umcproject/controller/NangmanLetterController.java
  src/main/java/aromanticcat/umcproject/dto/NangmanLetterDTO.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterService.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/RandomNicknameService.java
  src/test/java/aromanticcat/umcproject/service/NangmanLetterServiceTests.java
Labels: :sparkles:feat

#27 ✨ 낭만우편함 답장할 편지 조회 API 구현 완료
  src/main/java/aromanticcat/umcproject/converter/NangmanPostBoxConverter.java
  src/main/java/aromanticcat/umcproject/entity/NangmanReply.java
  src/main/java/aromanticcat/umcproject/service/NangmanPostBoxService.java
  src/main/java/aromanticcat/umcproject/service/NangmanPostBoxServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanPostBoxController.java
  src/main/java/aromanticcat/umcproject/web/dto/NangmanPostBoxRequestDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/NangmanPostBoxResponseDTO.java
  src/test/java/aromanticcat/umcproject/repository/NangmanLetterRepositoryTests.java
  src/test/java/aromanticcat/umcproject/service/NangmanLetterServiceTests.java
Labels: :sparkles:feat

#35 ✨ 낭만우편함 세부 기능 추가
  src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java
  src/main/java/aromanticcat/umcproject/entity/NangmanLetter.java
  src/main/java/aromanticcat/umcproject/repository/NangmanReplyRepository.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxService.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterService.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterController.java
  src/main/java/aromanticcat/umcproject/web/dto/NangmanLetterDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxRequestDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
Labels: :sparkles:feat

#38 :sparkles: 낭만우편함 나의 편지 목록 조회 API 구현 (로그인된 사용자 정보 얻는 부분 제외)
  src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxService.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
Labels: :sparkles:feat

#50 :sparkles: 내가 쓴 편지에 대한 답장 조회 API 구현
  src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java
  src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java
  src/main/java/aromanticcat/umcproject/repository/NangmanReplyRepository.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxService.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
Labels: :sparkles:feat

#52 :sparkles: 내가 쓴 답장(+연결된 원본 편지) 목록 조회 API 구현
  src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java
  src/main/java/aromanticcat/umcproject/repository/NangmanReplyRepository.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxService.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
Labels: :sparkles:feat

#57 ✨ 페이징 구현
  src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java
  src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java
  src/main/java/aromanticcat/umcproject/repository/NangmanReplyRepository.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxService.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java
Labels: :sparkles:feat

#59 Feat/23
  src/main/java/aromanticcat/umcproject/converter/FriendConverter.java
  src/main/java/aromanticcat/umcproject/entity/Friend.java
  src/main/java/aromanticcat/umcproject/entity/Letterbox.java
  src/main/java/aromanticcat/umcproject/entity/Member.java
  src/main/java/aromanticcat/umcproject/repository/LetterBoxRepository.java
  src/main/java/aromanticcat/umcproject/repository/MemberRepository.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandService.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendQueryServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/FriendController.java
  src/main/java/aromanticcat/umcproject/web/dto/Friend/FriendRequestDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/Friend/FriendResponseDTO.java
  src/main/resources/application.yml
Labels: :construction_worker: ci

#60 ✨ 낭만모음집 목록 조회 API
  src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java
  src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java
  src/main/java/aromanticcat/umcproject/service/NangmanCollectionService.java
  src/main/java/aromanticcat/umcproject/service/NangmanCollectionServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java
  src/main/java/aromanticcat/umcproject/web/dto/NangmanCollection/NangmanCollectionResponseDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
Labels: :sparkles:feat

#62 ✨ 낭만모음집 상세 조회 API 구현
  src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java
  src/main/java/aromanticcat/umcproject/entity/Member.java
  src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java
  src/main/java/aromanticcat/umcproject/repository/NangmanReplyRepository.java
  src/main/java/aromanticcat/umcproject/service/NangmanCollectionService.java
  src/main/java/aromanticcat/umcproject/service/NangmanCollectionServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
Labels: :sparkles:feat

#66 ✨ 상점 편지지 목록 조회 API 구현 완료
  src/main/java/aromanticcat/umcproject/converter/StoreConverter.java
  src/main/java/aromanticcat/umcproject/entity/AcquiredItem.java
  src/main/java/aromanticcat/umcproject/entity/ItemBox.java
  src/main/java/aromanticcat/umcproject/entity/LetterPaper.java
  src/main/java/aromanticcat/umcproject/entity/Member.java
  src/main/java/aromanticcat/umcproject/entity/Stamp.java
  src/main/java/aromanticcat/umcproject/repository/AcquiredItemRepository.java
  src/main/java/aromanticcat/umcproject/repository/LetterPaperRepository.java
  src/main/java/aromanticcat/umcproject/service/StoreService.java
  src/main/java/aromanticcat/umcproject/service/StoreServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanCollectionService.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanCollectionServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanLetterBoxService.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanLetterBoxServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java
  src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
  src/main/java/aromanticcat/umcproject/web/dto/NangmanCollection/NangmanCollectionResponseDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/store/StoreResponseDTO.java
Labels: :sparkles:feat

#68 :sparkles: 상점 우표 목록 조회 API 구현
  src/main/java/aromanticcat/umcproject/converter/StoreConverter.java
  src/main/java/aromanticcat/umcproject/repository/StampRepository.java
  src/main/java/aromanticcat/umcproject/service/StoreService.java
  src/main/java/aromanticcat/umcproject/service/StoreServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
  src/main/java/aromanticcat/umcproject/web/dto/store/StoreResponseDTO.java
Labels: :sparkles:feat

#72 ✨ 편지지/우표 구매 API
  src/main/java/aromanticcat/umcproject/converter/StoreConverter.java
  src/main/java/aromanticcat/umcproject/entity/Member.java
  src/main/java/aromanticcat/umcproject/repository/AcquiredItemRepository.java
  src/main/java/aromanticcat/umcproject/service/StoreService.java
  src/main/java/aromanticcat/umcproject/service/StoreServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
Labels: :sparkles:feat

#74 Feat/23
  src/main/java/aromanticcat/umcproject/converter/FriendConverter.java
  src/main/java/aromanticcat/umcproject/entity/Friend.java
  src/main/java/aromanticcat/umcproject/entity/FriendStatus.java
  src/main/java/aromanticcat/umcproject/repository/FriendRepository.java
  src/main/java/aromanticcat/umcproject/repository/LetterBoxRepository.java
  src/main/java/aromanticcat/umcproject/repository/MemberRepository.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandService.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendQueryService.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendQueryServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/FriendController.java
  src/main/java/aromanticcat/umcproject/web/dto/Friend/FriendRequestDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/Friend/FriendResponseDTO.java
Labels: :sparkles:feat

#79 Feat/29 우편함 생성
  src/main/java/aromanticcat/umcproject/entity/Letter.java
  src/main/java/aromanticcat/umcproject/entity/LetterPaper.java
  src/main/java/aromanticcat/umcproject/entity/Letterbox.java
  src/main/java/aromanticcat/umcproject/entity/Stamp.java
  src/main/java/aromanticcat/umcproject/repository/LetterBoxRepository.java
  src/main/java/aromanticcat/umcproject/service/StampService.java
  src/main/java/aromanticcat/umcproject/service/letterbox/LetterboxService.java
  src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java
  src/main/java/aromanticcat/umcproject/web/dto/LetterboxRequest.java
  src/main/java/aromanticcat/umcproject/web/dto/LetterboxResponse.java
Labels: :sparkles:feat

#80 Refactor/78 엔티티 수정 및 오류 해결
  src/main/java/aromanticcat/umcproject/entity/Letter.java
  src/main/java/aromanticcat/umcproject/entity/Letterbox.java
  src/main/java/aromanticcat/umcproject/entity/Member.java
  src/main/java/aromanticcat/umcproject/entity/Stamp.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandServiceImpl.java
Labels: :sparkles:feat

#82 Feat/29 우편함 조회
  src/main/java/aromanticcat/umcproject/entity/Letterbox.java
  src/main/java/aromanticcat/umcproject/repository/LetterBoxRepository.java
  src/main/java/aromanticcat/umcproject/service/letterbox/LetterboxService.java
  src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java
  src/main/java/aromanticcat/umcproject/web/dto/LetterboxResponse.java
Labels: :sparkles:feat

#83 :sparkles: Feat : 우편함 수정 API
  src/main/java/aromanticcat/umcproject/service/letterbox/LetterboxService.java
  src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java
  src/main/java/aromanticcat/umcproject/web/dto/LetterboxRequest.java
Labels: :sparkles:feat

#84 Feat/76 편지 생성, 조회 API
  src/main/java/aromanticcat/umcproject/entity/Letter.java
  src/main/java/aromanticcat/umcproject/entity/LetterPaper.java
  src/main/java/aromanticcat/umcproject/entity/Letterbox.java
  src/main/java/aromanticcat/umcproject/repository/LetterPaperRepository.java
  src/main/java/aromanticcat/umcproject/repository/LetterRepository.java
  src/main/java/aromanticcat/umcproject/repository/StampRepository.java
  src/main/java/aromanticcat/umcproject/service/letterbox/LetterService.java
  src/main/java/aromanticcat/umcproject/service/letterbox/LetterboxService.java
  src/main/java/aromanticcat/umcproject/web/controller/LetterController.java
  src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java
  src/main/java/aromanticcat/umcproject/web/dto/Letterbox/LetterRequest.java
  src/main/java/aromanticcat/umcproject/web/dto/Letterbox/LetterResponse.java
  src/main/java/aromanticcat/umcproject/web/dto/Letterbox/LetterboxRequest.java
  src/main/java/aromanticcat/umcproject/web/dto/Letterbox/LetterboxResponse.java
Labels: :sparkles:feat

#85 ♻️ 코드 리팩토링 + 낭만우편함 기능 수정
  src/main/java/aromanticcat/umcproject/converter/MyCollectionConverter.java
  src/main/java/aromanticcat/umcproject/converter/NangmanCollectionConverter.java
  src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java
  src/main/java/aromanticcat/umcproject/entity/NangmanLetter.java
  src/main/java/aromanticcat/umcproject/repository/AcquiredItemRepository.java
  src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java
  src/main/java/aromanticcat/umcproject/service/MyCollectionService.java
  src/main/java/aromanticcat/umcproject/service/MyCollectionServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/StoreService.java
  src/main/java/aromanticcat/umcproject/service/StoreServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanCollectionService.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanCollectionServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanLetterBoxService.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanLetterBoxServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/RandomNicknameService.java
  src/main/java/aromanticcat/umcproject/web/controller/MyCollectionController.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java
  src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
  src/main/java/aromanticcat/umcproject/web/dto/MyCollectionResponseDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanCollectionResponseDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxRequestDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
Labels: :sparkles:feat

#87 :pencil2: 파일명, 메소드명 변경
  src/main/java/aromanticcat/umcproject/converter/NangmanCollectionConverter.java
  src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanCollectionService.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanLetterBoxService.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanCollectionService.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanCollectionServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanLetterboxService.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanLetterboxServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/RandomNicknameService.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java
  src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterboxController.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterbox/NangmanCollectionResponseDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterbox/NangmanLetterBoxResponseDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterbox/NangmanLetterboxRequestDTO.java
Labels: :sparkles:feat

#88 주소록 관련 기능 개발 완료
  src/main/java/aromanticcat/umcproject/converter/FriendConverter.java
  src/main/java/aromanticcat/umcproject/entity/Friend.java
  src/main/java/aromanticcat/umcproject/entity/Letterbox.java
  src/main/java/aromanticcat/umcproject/repository/FriendRepository.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandService.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandServiceImpl.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendQueryService.java
  src/main/java/aromanticcat/umcproject/service/FriendService/FriendQueryServiceImpl.java
  src/main/java/aromanticcat/umcproject/web/controller/FriendController.java
  src/main/java/aromanticcat/umcproject/web/dto/Friend/FriendRequestDTO.java
  src/main/java/aromanticcat/umcproject/web/dto/Friend/FriendResponseDTO.java
Labels: bug, :sparkles:feat
